name: Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo ">>> 이동"
            cd /home/ubuntu/2025-2-CCD-1-DevCode-01/BE

            echo ">>> 최신 코드 받기"
            git pull origin main

            echo ">>> venv 로드"
            source venv/bin/activate

            echo ">>> 패키지 업데이트"
            pip install -r requirements.txt

            echo ">>> Django static 수집"
            python manage.py collectstatic --noinput

            echo ">>> Django DB 마이그레이션"
            python manage.py migrate

            echo ">>> Daphne 재시작"
            sudo systemctl daemon-reload
            sudo systemctl restart daphne

            echo ">>> nginx 재시작"
            sudo nginx -t
            sudo systemctl restart nginx

            echo ">>> 배포 완료!"
